title: "7 Gate Academy Machine Learning Cohort 1"
github_url: https://github.com/7-gate-academy-ml-program/Synopsis

exclude: ['vendor', 'setup.sh', 'jekyll.sh']

timezone: America/Los_Angeles
baseurl: /Synopsis

collections:

  students:
    output: true
    permalink: /students/:path/

  # alumni:
  #   output: true
  #   permalink: /alumni/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

  - scope:
      path: ""
      type: students
    values:
      layout: person

  # - scope:
  #     path: ""
  #     type: alumni
  #   values:
  #     layout: person

 

